# Generated by Django 3.1.7 on 2021-04-01 01:25

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_update_wine_search_word'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wine',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='catalog_wine_description_index', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='wine',
            index=django.contrib.postgres.indexes.GinIndex(fields=['variety'], name='catalog_wine_variety_index', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='wine',
            index=django.contrib.postgres.indexes.GinIndex(fields=['winery'], name='catalog_wine_winery_index', opclasses=['gin_trgm_ops']),
        ),
    ]
