version: "3.8"

services:

  database:
    container_name: perusable-database-prod
    environment:
      - POSTGRES_DB=perusable
      - POSTGRES_USER=perusable
      - POSTGRES_PASSWORD=perusable
    image: postgres:13.2
    ports:
      - 5433:5432
    volumes:
      - perusable-database-prod:/var/lib/postgresql/data

  elasticsearch:
    container_name: perusable-elasticsearch-prod
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    image: elasticsearch:7.10.1
    ports:
      - 9200:9200
    volumes:
      - perusable-elasticsearch-prod:/usr/share/elasticsearch/data

  server:
    build:
      context: ./server
    container_name: perusable-server-prod
    depends_on:
      - database
      - elasticsearch
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=perusable
      - SQL_USER=perusable
      - SQL_PASSWORD=perusable
      - SQL_HOST=perusable-database-prod
      - SQL_PORT=5432
      - ES_HOSTS=http://perusable-elasticsearch-prod:9200
    command: [ "bash", "start.prod.sh" ]
    ports:
      - 8000
    volumes:
      - ./server:/usr/src/app
      - static:/usr/src/app/static

  client:
    build:
      context: ./client
    command: [ "npm", "start" ]
    container_name: perusable-client-prod
    depends_on:
      - server
    ports:
      - 3000
    volumes:
      - ./client:/usr/src/app

  reverse-proxy:
    build:
      context: ./reverse-proxy
    container_name: perusable-reverse-proxy
    depends_on:
      - server
      - client
    ports:
      - 8003:80
    restart: always
    volumes:
      - static:/usr/src/app/static

volumes:
  perusable-database-prod:
  perusable-elasticsearch-prod:
  static:
