version: "3.8"

services:

  database:
    container_name: perusable-database
    environment:
      - POSTGRES_DB=perusable
      - POSTGRES_USER=perusable
      - POSTGRES_PASSWORD=perusable
    image: postgres:14.1
    ports:
      - "5433:5432"
    volumes:
      - perusable-database:/var/lib/postgresql/data

  elasticsearch:
    container_name: perusable-elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    image: elasticsearch:7.10.1
    ports:
      - 9200:9200
    volumes:
      - perusable-elasticsearch:/usr/share/elasticsearch/data

  server:
    build:
      context: ./server
    container_name: perusable-server
    depends_on:
      - database
      - elasticsearch
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=perusable
      - SQL_USER=perusable
      - SQL_PASSWORD=perusable
      - SQL_HOST=perusable-database
      - SQL_PORT=5432
      - ES_HOSTS=http://perusable-elasticsearch:9200
    command: [ "bash", "start.sh" ]
    ports:
      - 8003:8000
    volumes:
      - ./server:/usr/src/app

  client:
    build:
      context: ./client
    command: [ "npm", "start" ]
    container_name: perusable-client
    depends_on:
      - server
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app

volumes:
  perusable-database:
  perusable-elasticsearch:
